pipeline {
   agent any

   stages {
      stage('checkout') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/SrinivasanTarget/ContractTestingBoilerplate']]])
         }
      }

      stage('Run Provider Verify Test') {
         steps {
             sh 'mvn clean -Dtest=PactAgeProviderTest test -pl date-provider'
        }
      }
   }


}